sudo: false

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - build-essential
      - automake
      - autoconf
      - autopoint
      - libtool
      - gettext
      - selinux-policy-dev
      - libselinux1
      - pkg-config

script:
 - ./autogen.sh
 - make

# vim:et:ts=2:sw=2
