sudo: false

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - autopoint
      - xsltproc

script:
 - ./autogen.sh --without-selinux --disable-man
 - make

# vim:et:ts=2:sw=2
